name: Java/GraalVM

on: workflow_dispatch

jobs:
    install:
        strategy:
            matrix:
                os: [ ubuntu-22.04, windows-2022 ]
        runs-on: ${{ matrix.os }}
        steps:
          - name: Checkout
            uses: actions/checkout@v3
          - name: Setup GraalVM
            uses: graalvm/setup-graalvm@v1
            with:
                java-version: 20
                distribution: 'graalvm'
                components: 'icu4j,jipher,js,llvm-toolchain,nodejs,regex,visualvm'
                github-token: ${{ secrets.GITHUB_TOKEN }}
          - name: Linux Part
            if: ${{ matrix.os == 'ubuntu-22.04' }}
            run: |
              echo JAVA_HOME = $JAVA_HOME
              gu list
              find . -type d -name "Linux" -exec rm -rf {} \;
              cp -r $JAVA_HOME Linux
              ls Linux
            working-directory: Java/GraalVM/
          - name: Windows List Components
            if: ${{ matrix.os == 'windows-2022' }}
            run: |
              cmd /c "echo JAVA_HOME = %JAVA_HOME%"
              cmd /c "gu list"
              Remove-Item -LiteralPath "Windows" -Force -Recurse
              Copy-Item -Path "$Env.JAVA_HOME" -Destination "Windows" -Recurse
              Get-ChildItem -Path "Windows" -Name
            working-directory: Java/GraalVM/
