name: Java/GraalVM

on: workflow_dispatch

jobs:
    install-linux:
        name: Get Linux
        runs-on: ubuntu-22.04
        steps:
          - name: Checkout
            uses: actions/checkout@v3
          - name: Setup GraalVM
            uses: graalvm/setup-graalvm@v1
            with:
                java-version: 20
                distribution: 'graalvm'
                components: 'icu4j,jipher,js,llvm-toolchain,nodejs,regex,visualvm'
                github-token: ${{ secrets.GITHUB_TOKEN }}
          - name: List Components
            run: |
              echo JAVA_HOME = $JAVA_HOME
              gu list
            working-directory: Java/GraalVM/
          - name: Copy GraalVM distribution
            run: |
              cp -r $JAVA_HOME Linux
              ls Linux
            working-directory: Java/GraalVM/
          - name: Upload GraalVM distribution
            uses: actions/upload-artifact@v3
            with:
                name: java_graalvm_linux
                path: Java/GraalVM/Linux
                if-no-files-found: ignore

    install-windows:
        name: Get Windows
        runs-on: windows-2022
        steps:
          - name: Checkout
            uses: actions/checkout@v3
          - name: Setup GraalVM
            uses: graalvm/setup-graalvm@v1
            with:
                java-version: 20
                distribution: 'graalvm'
                components: 'icu4j,jipher,js,llvm-toolchain,nodejs,regex,visualvm'
                github-token: ${{ secrets.GITHUB_TOKEN }}
          - name: List Components
            run: |
              cmd /c "echo JAVA_HOME = %JAVA_HOME%"
              cmd /c "gu list"
            working-directory: Java/GraalVM/
          - name: Copy GraalVM distribution
            run: |
              cmd /c "xcopy %JAVA_HOME% Windows /q /i /e"
              Get-ChildItem -Path "Windows" -Name
            working-directory: Java/GraalVM/
          - name: Upload GraalVM distribution
            uses: actions/upload-artifact@v3
            with:
                name: java_graalvm_windows
                path: Java/GraalVM/Windows
                if-no-files-found: ignore
