name: GraalVM

on: workflow_dispatch

jobs:
    get:
        strategy:
            matrix:
                os: [ ubuntu-22.04, windows-2022 ]
        runs-on: ${{ matrix.os }}
        steps:
          - name: Checkout
            uses: actions/checkout@v3
          - name: Setup GraalVM
            uses: graalvm/setup-graalvm@v1
            with:
                java-version: 20
                distribution: 'graalvm'
                components: 'icu4j,jipher,js,llvm-toolchain,nodejs,regex,visualvm'
                github-token: ${{ secrets.GITHUB_TOKEN }}
          - name: Linux Part
            if: ${{ matrix.os == 'ubuntu-22.04' }}
            run: |
              echo JAVA_HOME = $JAVA_HOME
              gu list
              rm -R Java/GraalVM/Linux
              cp -r $JAVA_HOME Java/GraalVM/Linux
              ls Java/GraalVM/Linux
          - name: Windows List Components
            if: ${{ matrix.os == 'windows-2022' }}
            run: |
              cmd /c "echo JAVA_HOME = %JAVA_HOME%"
              cmd /c "gu list"
